// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/reconciler/v1/reconciler.proto

package reconcilerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionState int32

const (
	TransactionState_TRANSACTION_STATE_UNKNOWN        TransactionState = 0
	TransactionState_TRANSACTION_STATE_COMMITTED      TransactionState = 1
	TransactionState_TRANSACTION_STATE_ABORTED        TransactionState = 2
	TransactionState_TRANSACTION_STATE_ONGOING        TransactionState = 3
	TransactionState_TRANSACTION_STATE_PREPARE_COMMIT TransactionState = 4
	TransactionState_TRANSACTION_STATE_PREPARE_ABORT  TransactionState = 5
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRANSACTION_STATE_UNKNOWN",
		1: "TRANSACTION_STATE_COMMITTED",
		2: "TRANSACTION_STATE_ABORTED",
		3: "TRANSACTION_STATE_ONGOING",
		4: "TRANSACTION_STATE_PREPARE_COMMIT",
		5: "TRANSACTION_STATE_PREPARE_ABORT",
	}
	TransactionState_value = map[string]int32{
		"TRANSACTION_STATE_UNKNOWN":        0,
		"TRANSACTION_STATE_COMMITTED":      1,
		"TRANSACTION_STATE_ABORTED":        2,
		"TRANSACTION_STATE_ONGOING":        3,
		"TRANSACTION_STATE_PREPARE_COMMIT": 4,
		"TRANSACTION_STATE_PREPARE_ABORT":  5,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_reconciler_v1_reconciler_proto_enumTypes[0].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_api_reconciler_v1_reconciler_proto_enumTypes[0]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{0}
}

type DescribeTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BrokerList      string                 `protobuf:"bytes,1,opt,name=broker_list,json=brokerList,proto3" json:"broker_list,omitempty"`                // "broker1:9092,broker2 9092"
	TransactionalId string                 `protobuf:"bytes,2,opt,name=transactional_id,json=transactionalId,proto3" json:"transactional_id,omitempty"` // "numaflow-gen1-epoch42"
	TimeoutMs       int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`                  // 10000 (10s)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeTransactionRequest) Reset() {
	*x = DescribeTransactionRequest{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTransactionRequest) ProtoMessage() {}

func (x *DescribeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTransactionRequest.ProtoReflect.Descriptor instead.
func (*DescribeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeTransactionRequest) GetBrokerList() string {
	if x != nil {
		return x.BrokerList
	}
	return ""
}

func (x *DescribeTransactionRequest) GetTransactionalId() string {
	if x != nil {
		return x.TransactionalId
	}
	return ""
}

func (x *DescribeTransactionRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DescribeTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TransactionState       `protobuf:"varint,1,opt,name=state,proto3,enum=reconciler.v1.TransactionState" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Non-empty if request failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTransactionResponse) Reset() {
	*x = DescribeTransactionResponse{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTransactionResponse) ProtoMessage() {}

func (x *DescribeTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTransactionResponse.ProtoReflect.Descriptor instead.
func (*DescribeTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeTransactionResponse) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_TRANSACTION_STATE_UNKNOWN
}

func (x *DescribeTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AbortTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BrokerList      string                 `protobuf:"bytes,1,opt,name=broker_list,json=brokerList,proto3" json:"broker_list,omitempty"`
	TransactionalId string                 `protobuf:"bytes,2,opt,name=transactional_id,json=transactionalId,proto3" json:"transactional_id,omitempty"`
	ProducerEpoch   int32                  `protobuf:"varint,3,opt,name=producer_epoch,json=producerEpoch,proto3" json:"producer_epoch,omitempty"`
	TimeoutMs       int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AbortTransactionRequest) Reset() {
	*x = AbortTransactionRequest{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionRequest) ProtoMessage() {}

func (x *AbortTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTransactionRequest.ProtoReflect.Descriptor instead.
func (*AbortTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{2}
}

func (x *AbortTransactionRequest) GetBrokerList() string {
	if x != nil {
		return x.BrokerList
	}
	return ""
}

func (x *AbortTransactionRequest) GetTransactionalId() string {
	if x != nil {
		return x.TransactionalId
	}
	return ""
}

func (x *AbortTransactionRequest) GetProducerEpoch() int32 {
	if x != nil {
		return x.ProducerEpoch
	}
	return 0
}

func (x *AbortTransactionRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type AbortTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTransactionResponse) Reset() {
	*x = AbortTransactionResponse{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionResponse) ProtoMessage() {}

func (x *AbortTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTransactionResponse.ProtoReflect.Descriptor instead.
func (*AbortTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{3}
}

func (x *AbortTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListConsumerGroupOffsetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerList    string                 `protobuf:"bytes,1,opt,name=broker_list,json=brokerList,proto3" json:"broker_list,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topics        []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumerGroupOffsetsRequest) Reset() {
	*x = ListConsumerGroupOffsetsRequest{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumerGroupOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumerGroupOffsetsRequest) ProtoMessage() {}

func (x *ListConsumerGroupOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumerGroupOffsetsRequest.ProtoReflect.Descriptor instead.
func (*ListConsumerGroupOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{4}
}

func (x *ListConsumerGroupOffsetsRequest) GetBrokerList() string {
	if x != nil {
		return x.BrokerList
	}
	return ""
}

func (x *ListConsumerGroupOffsetsRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *ListConsumerGroupOffsetsRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ListConsumerGroupOffsetsRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ListConsumerGroupOffsetsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartitionOffsets map[string]int64       `protobuf:"bytes,1,rep,name=partition_offsets,json=partitionOffsets,proto3" json:"partition_offsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // "topic-partition" -> offset
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListConsumerGroupOffsetsResponse) Reset() {
	*x = ListConsumerGroupOffsetsResponse{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumerGroupOffsetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumerGroupOffsetsResponse) ProtoMessage() {}

func (x *ListConsumerGroupOffsetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumerGroupOffsetsResponse.ProtoReflect.Descriptor instead.
func (*ListConsumerGroupOffsetsResponse) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{5}
}

func (x *ListConsumerGroupOffsetsResponse) GetPartitionOffsets() map[string]int64 {
	if x != nil {
		return x.PartitionOffsets
	}
	return nil
}

func (x *ListConsumerGroupOffsetsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_reconciler_v1_reconciler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_reconciler_v1_reconciler_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_api_reconciler_v1_reconciler_proto protoreflect.FileDescriptor

const file_api_reconciler_v1_reconciler_proto_rawDesc = "" +
	"\n" +
	"\"api/reconciler/v1/reconciler.proto\x12\rreconciler.v1\"\x87\x01\n" +
	"\x1aDescribeTransactionRequest\x12\x1f\n" +
	"\vbroker_list\x18\x01 \x01(\tR\n" +
	"brokerList\x12)\n" +
	"\x10transactional_id\x18\x02 \x01(\tR\x0ftransactionalId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"j\n" +
	"\x1bDescribeTransactionResponse\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1f.reconciler.v1.TransactionStateR\x05state\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xab\x01\n" +
	"\x17AbortTransactionRequest\x12\x1f\n" +
	"\vbroker_list\x18\x01 \x01(\tR\n" +
	"brokerList\x12)\n" +
	"\x10transactional_id\x18\x02 \x01(\tR\x0ftransactionalId\x12%\n" +
	"\x0eproducer_epoch\x18\x03 \x01(\x05R\rproducerEpoch\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"J\n" +
	"\x18AbortTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa0\x01\n" +
	"\x1fListConsumerGroupOffsetsRequest\x12\x1f\n" +
	"\vbroker_list\x18\x01 \x01(\tR\n" +
	"brokerList\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\xf1\x01\n" +
	" ListConsumerGroupOffsetsResponse\x12r\n" +
	"\x11partition_offsets\x18\x01 \x03(\v2E.reconciler.v1.ListConsumerGroupOffsetsResponse.PartitionOffsetsEntryR\x10partitionOffsets\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1aC\n" +
	"\x15PartitionOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"k\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds*\xdb\x01\n" +
	"\x10TransactionState\x12\x1d\n" +
	"\x19TRANSACTION_STATE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bTRANSACTION_STATE_COMMITTED\x10\x01\x12\x1d\n" +
	"\x19TRANSACTION_STATE_ABORTED\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATE_ONGOING\x10\x03\x12$\n" +
	" TRANSACTION_STATE_PREPARE_COMMIT\x10\x04\x12#\n" +
	"\x1fTRANSACTION_STATE_PREPARE_ABORT\x10\x052\xa8\x03\n" +
	"\x0fKafkaReconciler\x12l\n" +
	"\x13DescribeTransaction\x12).reconciler.v1.DescribeTransactionRequest\x1a*.reconciler.v1.DescribeTransactionResponse\x12c\n" +
	"\x10AbortTransaction\x12&.reconciler.v1.AbortTransactionRequest\x1a'.reconciler.v1.AbortTransactionResponse\x12{\n" +
	"\x18ListConsumerGroupOffsets\x12..reconciler.v1.ListConsumerGroupOffsetsRequest\x1a/.reconciler.v1.ListConsumerGroupOffsetsResponse\x12E\n" +
	"\x06Health\x12\x1c.reconciler.v1.HealthRequest\x1a\x1d.reconciler.v1.HealthResponseBVZTgithub.com/numaproj/numaflow/kafka-reconciler-sidecar/api/reconciler/v1;reconcilerv1b\x06proto3"

var (
	file_api_reconciler_v1_reconciler_proto_rawDescOnce sync.Once
	file_api_reconciler_v1_reconciler_proto_rawDescData []byte
)

func file_api_reconciler_v1_reconciler_proto_rawDescGZIP() []byte {
	file_api_reconciler_v1_reconciler_proto_rawDescOnce.Do(func() {
		file_api_reconciler_v1_reconciler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reconciler_v1_reconciler_proto_rawDesc), len(file_api_reconciler_v1_reconciler_proto_rawDesc)))
	})
	return file_api_reconciler_v1_reconciler_proto_rawDescData
}

var file_api_reconciler_v1_reconciler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_reconciler_v1_reconciler_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_reconciler_v1_reconciler_proto_goTypes = []any{
	(TransactionState)(0),                    // 0: reconciler.v1.TransactionState
	(*DescribeTransactionRequest)(nil),       // 1: reconciler.v1.DescribeTransactionRequest
	(*DescribeTransactionResponse)(nil),      // 2: reconciler.v1.DescribeTransactionResponse
	(*AbortTransactionRequest)(nil),          // 3: reconciler.v1.AbortTransactionRequest
	(*AbortTransactionResponse)(nil),         // 4: reconciler.v1.AbortTransactionResponse
	(*ListConsumerGroupOffsetsRequest)(nil),  // 5: reconciler.v1.ListConsumerGroupOffsetsRequest
	(*ListConsumerGroupOffsetsResponse)(nil), // 6: reconciler.v1.ListConsumerGroupOffsetsResponse
	(*HealthRequest)(nil),                    // 7: reconciler.v1.HealthRequest
	(*HealthResponse)(nil),                   // 8: reconciler.v1.HealthResponse
	nil,                                      // 9: reconciler.v1.ListConsumerGroupOffsetsResponse.PartitionOffsetsEntry
}
var file_api_reconciler_v1_reconciler_proto_depIdxs = []int32{
	0, // 0: reconciler.v1.DescribeTransactionResponse.state:type_name -> reconciler.v1.TransactionState
	9, // 1: reconciler.v1.ListConsumerGroupOffsetsResponse.partition_offsets:type_name -> reconciler.v1.ListConsumerGroupOffsetsResponse.PartitionOffsetsEntry
	1, // 2: reconciler.v1.KafkaReconciler.DescribeTransaction:input_type -> reconciler.v1.DescribeTransactionRequest
	3, // 3: reconciler.v1.KafkaReconciler.AbortTransaction:input_type -> reconciler.v1.AbortTransactionRequest
	5, // 4: reconciler.v1.KafkaReconciler.ListConsumerGroupOffsets:input_type -> reconciler.v1.ListConsumerGroupOffsetsRequest
	7, // 5: reconciler.v1.KafkaReconciler.Health:input_type -> reconciler.v1.HealthRequest
	2, // 6: reconciler.v1.KafkaReconciler.DescribeTransaction:output_type -> reconciler.v1.DescribeTransactionResponse
	4, // 7: reconciler.v1.KafkaReconciler.AbortTransaction:output_type -> reconciler.v1.AbortTransactionResponse
	6, // 8: reconciler.v1.KafkaReconciler.ListConsumerGroupOffsets:output_type -> reconciler.v1.ListConsumerGroupOffsetsResponse
	8, // 9: reconciler.v1.KafkaReconciler.Health:output_type -> reconciler.v1.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_reconciler_v1_reconciler_proto_init() }
func file_api_reconciler_v1_reconciler_proto_init() {
	if File_api_reconciler_v1_reconciler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reconciler_v1_reconciler_proto_rawDesc), len(file_api_reconciler_v1_reconciler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reconciler_v1_reconciler_proto_goTypes,
		DependencyIndexes: file_api_reconciler_v1_reconciler_proto_depIdxs,
		EnumInfos:         file_api_reconciler_v1_reconciler_proto_enumTypes,
		MessageInfos:      file_api_reconciler_v1_reconciler_proto_msgTypes,
	}.Build()
	File_api_reconciler_v1_reconciler_proto = out.File
	file_api_reconciler_v1_reconciler_proto_goTypes = nil
	file_api_reconciler_v1_reconciler_proto_depIdxs = nil
}
