// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/reconciler/v1/reconciler.proto

package reconcilerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KafkaReconciler_DescribeTransaction_FullMethodName      = "/reconciler.v1.KafkaReconciler/DescribeTransaction"
	KafkaReconciler_AbortTransaction_FullMethodName         = "/reconciler.v1.KafkaReconciler/AbortTransaction"
	KafkaReconciler_ListConsumerGroupOffsets_FullMethodName = "/reconciler.v1.KafkaReconciler/ListConsumerGroupOffsets"
	KafkaReconciler_Health_FullMethodName                   = "/reconciler.v1.KafkaReconciler/Health"
)

// KafkaReconcilerClient is the client API for KafkaReconciler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KafkaReconciler provides Kafka Admin API for transaction reconciliation
type KafkaReconcilerClient interface {
	// Describe transaction state via Kafka Admin API
	DescribeTransaction(ctx context.Context, in *DescribeTransactionRequest, opts ...grpc.CallOption) (*DescribeTransactionResponse, error)
	// Abort an ongoing transaction
	AbortTransaction(ctx context.Context, in *AbortTransactionRequest, opts ...grpc.CallOption) (*AbortTransactionResponse, error)
	// List consumer group offsets for alignment verification
	ListConsumerGroupOffsets(ctx context.Context, in *ListConsumerGroupOffsetsRequest, opts ...grpc.CallOption) (*ListConsumerGroupOffsetsResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type kafkaReconcilerClient struct {
	cc grpc.ClientConnInterface
}

func NewKafkaReconcilerClient(cc grpc.ClientConnInterface) KafkaReconcilerClient {
	return &kafkaReconcilerClient{cc}
}

func (c *kafkaReconcilerClient) DescribeTransaction(ctx context.Context, in *DescribeTransactionRequest, opts ...grpc.CallOption) (*DescribeTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTransactionResponse)
	err := c.cc.Invoke(ctx, KafkaReconciler_DescribeTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kafkaReconcilerClient) AbortTransaction(ctx context.Context, in *AbortTransactionRequest, opts ...grpc.CallOption) (*AbortTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortTransactionResponse)
	err := c.cc.Invoke(ctx, KafkaReconciler_AbortTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kafkaReconcilerClient) ListConsumerGroupOffsets(ctx context.Context, in *ListConsumerGroupOffsetsRequest, opts ...grpc.CallOption) (*ListConsumerGroupOffsetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumerGroupOffsetsResponse)
	err := c.cc.Invoke(ctx, KafkaReconciler_ListConsumerGroupOffsets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kafkaReconcilerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, KafkaReconciler_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KafkaReconcilerServer is the server API for KafkaReconciler service.
// All implementations must embed UnimplementedKafkaReconcilerServer
// for forward compatibility.
//
// KafkaReconciler provides Kafka Admin API for transaction reconciliation
type KafkaReconcilerServer interface {
	// Describe transaction state via Kafka Admin API
	DescribeTransaction(context.Context, *DescribeTransactionRequest) (*DescribeTransactionResponse, error)
	// Abort an ongoing transaction
	AbortTransaction(context.Context, *AbortTransactionRequest) (*AbortTransactionResponse, error)
	// List consumer group offsets for alignment verification
	ListConsumerGroupOffsets(context.Context, *ListConsumerGroupOffsetsRequest) (*ListConsumerGroupOffsetsResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedKafkaReconcilerServer()
}

// UnimplementedKafkaReconcilerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKafkaReconcilerServer struct{}

func (UnimplementedKafkaReconcilerServer) DescribeTransaction(context.Context, *DescribeTransactionRequest) (*DescribeTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeTransaction not implemented")
}
func (UnimplementedKafkaReconcilerServer) AbortTransaction(context.Context, *AbortTransactionRequest) (*AbortTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortTransaction not implemented")
}
func (UnimplementedKafkaReconcilerServer) ListConsumerGroupOffsets(context.Context, *ListConsumerGroupOffsetsRequest) (*ListConsumerGroupOffsetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsumerGroupOffsets not implemented")
}
func (UnimplementedKafkaReconcilerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedKafkaReconcilerServer) mustEmbedUnimplementedKafkaReconcilerServer() {}
func (UnimplementedKafkaReconcilerServer) testEmbeddedByValue()                         {}

// UnsafeKafkaReconcilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KafkaReconcilerServer will
// result in compilation errors.
type UnsafeKafkaReconcilerServer interface {
	mustEmbedUnimplementedKafkaReconcilerServer()
}

func RegisterKafkaReconcilerServer(s grpc.ServiceRegistrar, srv KafkaReconcilerServer) {
	// If the following call panics, it indicates UnimplementedKafkaReconcilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KafkaReconciler_ServiceDesc, srv)
}

func _KafkaReconciler_DescribeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaReconcilerServer).DescribeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KafkaReconciler_DescribeTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaReconcilerServer).DescribeTransaction(ctx, req.(*DescribeTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KafkaReconciler_AbortTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaReconcilerServer).AbortTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KafkaReconciler_AbortTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaReconcilerServer).AbortTransaction(ctx, req.(*AbortTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KafkaReconciler_ListConsumerGroupOffsets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumerGroupOffsetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaReconcilerServer).ListConsumerGroupOffsets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KafkaReconciler_ListConsumerGroupOffsets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaReconcilerServer).ListConsumerGroupOffsets(ctx, req.(*ListConsumerGroupOffsetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KafkaReconciler_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaReconcilerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KafkaReconciler_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaReconcilerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KafkaReconciler_ServiceDesc is the grpc.ServiceDesc for KafkaReconciler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KafkaReconciler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reconciler.v1.KafkaReconciler",
	HandlerType: (*KafkaReconcilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeTransaction",
			Handler:    _KafkaReconciler_DescribeTransaction_Handler,
		},
		{
			MethodName: "AbortTransaction",
			Handler:    _KafkaReconciler_AbortTransaction_Handler,
		},
		{
			MethodName: "ListConsumerGroupOffsets",
			Handler:    _KafkaReconciler_ListConsumerGroupOffsets_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _KafkaReconciler_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/reconciler/v1/reconciler.proto",
}
